# Generated by Django 5.1.5 on 2025-01-25 18:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('drone_model', models.CharField(choices=[('lightweight', 'Lightweight'), ('middleweight', 'Middleweight'), ('cruiserweight', 'Cruiserweight'), ('heavyweight', 'Heavyweight')], default='', max_length=30)),
                ('weight_limit', models.FloatField(validators=[django.core.validators.MaxValueValidator(500.0)])),
                ('battery_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('state', models.CharField(choices=[('idle', 'IDLE'), ('loading', 'LOADING'), ('loaded', 'LOADED'), ('delivering', 'DELIVERING'), ('delivered', 'DELIVERED'), ('returning', 'RETURNING')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('code', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='med_images/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drone.drone')),
            ],
        ),
    ]
