# Generated by Django 5.1.5 on 2025-01-28 17:17

import django.core.validators
import django.db.models.deletion
import enumfields.fields
import src.drone.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('drone_model', enumfields.fields.EnumField(default='Lightweight', enum=src.drone.enums.DroneModel, max_length=30)),
                ('weight_limit', models.DecimalField(decimal_places=1, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500.0)])),
                ('battery_capacity', models.DecimalField(decimal_places=1, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('state', enumfields.fields.EnumField(default='Idle', enum=src.drone.enums.DroneState, max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_time_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DroneBatteryLogHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_capacity', models.DecimalField(decimal_places=1, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone.drone')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid Format', regex='^(?=.*[a-zA-Z0-9])[a-zA-Z0-9-_]+$')])),
                ('weight', models.DecimalField(decimal_places=1, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('code', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Format', regex='^(?=.*[a-zA-Z0-9])[a-zA-Z0-9_]+$')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='med_images/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='drone.drone')),
            ],
        ),
    ]
