# Generated by Django 5.1.5 on 2025-01-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0005_alter_medication_drone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='med_images/'),
        ),
    ]
