# Generated by Django 5.1.5 on 2025-01-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0006_alter_medication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='last_time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
