# Generated by Django 5.1.5 on 2025-01-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0007_drone_last_time_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='last_time_updated',
            field=models.DateTimeField(),
        ),
    ]
