# Generated by Django 5.1.5 on 2025-01-26 17:16

import enumfields.fields
import src.drone.enums
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0008_alter_drone_last_time_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='drone_model',
            field=enumfields.fields.EnumField(default='Lightweight', enum=src.drone.enums.DroneModel, max_length=30),
        ),
        migrations.AlterField(
            model_name='drone',
            name='state',
            field=enumfields.fields.EnumField(default='Idle', enum=src.drone.enums.DroneState, max_length=20),
        ),
    ]
