# Generated by Django 5.1.5 on 2025-01-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0009_alter_drone_drone_model_alter_drone_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='last_time_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
