# Generated by Django 5.1.5 on 2025-01-27 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0015_dronebatteryloghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name should only have upper case letters, numbers, special character', regex='^[A-Z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name should only have letters, numbers, special character', regex='^[A-Za-z0-9_-]+$')]),
        ),
    ]
