# Generated by Django 5.1.5 on 2025-01-27 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0017_alter_medication_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name should only have upper case letters, numbers, special character', regex='^(?=.*[a-zA-Z0-9])[a-zA-Z0-9\\_]+$')]),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name should only have letters, numbers, special character', regex='^(?=.*[a-zA-Z0-9])[a-zA-Z0-9\\-_]+$')]),
        ),
    ]
